#!/bin/bash

use_rp=true

m=1024
n=1024
r=10
niter_ap=1000

method_lr=2

niter_maxvol=10
thresh=1.05
kc=2*$r
kr=2*$r

executable="../../build/gnu-release-lapack/bin/matrix_uniform"
if [ $method_lr = 1 ]; then
    filename="svd"
elif [ $method_lr = 2 ]; then
    filename="vol"
else
    filename="pvol"
fi

if [ "$use_rp" = false ]; then
    filename="${filename}_ap"
    method_ap=1
else
    filename="${filename}_rp"
    method_ap=2
fi

for seed in {1..1}
do
    $executable $seed $m $n $r $method_ap $niter_ap $method_lr \
        $niter_maxvol $thresh $kc $kr > "./${filename}/${filename}_${seed}.log"
done
